### ISSUE TITLE
Meaning of the --C and --T in the GSE141064 data

### ISSUE THREAD

**Issue by fanyue322** [songjiajia2018/Well-TEMP-Seq#1]
Dear @songjiajia2018 

Thanks for your nice work~ I wonder if you could explain the suffix (i.e. --C/--T) of the gene names in the TC matrix?

For example, if I want to perform the differentially expressed analysis as what you have done in Figure 3e, what should I do to preprocess those matrixes? I think the dataset you provided is really fascinating !

Best wishes!

**Comment by Quinn-zhang** [comment]
Hi fanyue,

The suffix --C means that this is an existed mRNA and --T means that this is a new-born mRNA. For DE analysis, we split the expression matrix into new and old, and we used the new-born one to do analysis.

**Comment by fanyue322** [comment]
@Quinn-zhang ,

Many thanks!
